"""testing character localtion

Revision ID: 277a67399247
Revises: 15cde4fac7fd
Create Date: 2020-10-19 00:04:24.997312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277a67399247'
down_revision = '15cde4fac7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_character_character_name', table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_character_character_name', 'character', ['character_name'], unique=False)
    # ### end Alembic commands ###
